version: '3'
services:
# mysql
  mysql:
    image: mysql:5.7
    container_name: moon_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - 3306:3306